version: "3.9"
services:
  api:
    volumes:
      - .:/src/
      - ./volumes/gradle-cache:/home/gradle/.gradle
      - /src/.gradle
      - /src/build
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "5005:5005"
    command: tail -f /dev/null